users:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /

home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

queue:
    resource: "@QueueBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@HomeBundle/Controller/"
    type:     annotation
